package api_test

// errorcodes_test.go renders the `error` code vocabulary this package can put
// on the wire, and it is mounted-routes.json's sibling.
//
// The reason it exists is an incident rather than a principle. #51 removed
// `403 not_an_approver` from the approval surface; the console went on
// branching on it and stayed green, because the console's tests stub responses
// and a stub says whatever the test wrote. Nothing compared the two sides. The
// endpoint *set* has been machine-checked since #44 — internal/runtime renders
// the assembled registry into internal/release/testdata/mounted-routes.json and
// internal/release/routes_test.go compares it against the contract document —
// and the error vocabulary, which is the axis that actually broke, had no such
// check.
//
// It is not a type generation problem, which is why no generator was added. The
// console's TypeScript was internally consistent the entire time the branch was
// dead: generated types match field *shapes*, and no shape says whether a code
// can still be emitted. What says that is a set difference, and a set
// difference needs both sides enumerated. This file enumerates the server's.
//
// # Why it is derived and not written down
//
// A hand-written list goes wrong together with the thing it guards. This
// repository has already paid for that once, in a hand-written role-to-surface
// map in internal/release/chart_test.go that was wrong in exactly the way the
// chart it checked was wrong. So the list here is read out of the package's own
// syntax tree:
//
//   - every writeError(w, status, code, message) call site, and
//   - every return of the (status int, code, message string) tables —
//     approvalError, auditReadError, decisionError, mfaError and
//     noSuchDecision — whose codes are values and therefore appear at no call
//     site as a literal at all. Counting writeError literals alone undercounts,
//     which is the trap this scanner exists to avoid falling into.
//
// The surface a code can reach is derived the same way: the Routes() methods
// say which listener each handler is mounted on, and the intra-package call
// graph carries that surface to every function the handler reaches. A code the
// console can never receive is not a code the console has to handle, and the
// exemption list on the console side depends on being able to say which is
// which.
//
// # What it does not cover
//
// The scanner reads syntax, not types. It resolves a code that is a string
// literal or a package-level string constant; anything else fails the run
// rather than being dropped, because a scanner that silently skips what it does
// not understand is how an artifact ends up shorter than the truth. It says
// nothing about which codes are *reachable* at runtime — an error table row for
// a sentinel nothing returns any more is still counted, because proving
// otherwise is a whole-program question and the failure mode it would catch
// (a code the console handles that the server never actually raises) is far
// milder than the one this closes.

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"net/http"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"testing"

	"github.com/d0lim/stamp/internal/api"
)

// errorCodeFile is where the rendered vocabulary lands.
//
// It sits beside public-endpoints.json rather than under
// internal/release/testdata, and the reason is D19: the console is embedded in
// the binary but embedding must not foreclose pulling it back out, so
// everything the console's own checks read has to travel with console/. The
// alternative — the artifact under internal/release with the Node check
// reaching up out of console/ — would make the console un-extractable for the
// sake of a directory name. internal/release/errorcodes_test.go reads it from
// here, the way internal/release/routes_test.go reads a contract document that
// also lives outside its own package.
const errorCodeFile = "../../console/contract/error-codes.json"

const errorCodeNote = "Generated by TestErrorCodeFileIsUpToDate in internal/api, read out of the " +
	"package's syntax tree: every writeError call site and every (status, code, message) error " +
	"table. Edit the handlers, not this file. console/scripts/check-contract.mjs compares it " +
	"against the codes the console branches on, in both directions."

// errorCodeDocumentVersion identifies the shape of this document, not the code
// set. The Node side refuses a version it does not understand rather than
// guessing at unfamiliar fields, which is the same rule public-endpoints.json
// follows.
const errorCodeDocumentVersion = 1

// emittedCode is one `error` code, with every HTTP status it is written under
// and every listener it can reach.
//
// Statuses are a set rather than one value because a code legitimately has more
// than one: `invalid_request` is a 400 when a body is malformed and a 413 when
// it is too large, and collapsing that would hide a real difference the moment
// somebody looked here to answer "what does this code mean".
type emittedCode struct {
	Code     string   `json:"code"`
	Statuses []int    `json:"statuses"`
	Surfaces []string `json:"surfaces"`
}

type errorCodeDocument struct {
	Version  int           `json:"version"`
	Note     string        `json:"note"`
	Surfaces []string      `json:"surfaces"`
	Codes    []emittedCode `json:"codes"`
}

// ---------------------------------------------------------------------------
// the scan
// ---------------------------------------------------------------------------

// funcKey names a function inside the package: "Type.Method" for a method,
// "Func" for a package-level function, and "Type.Method$N" for a function
// literal written inside one. Names are enough because this is one package and
// a method name is unique within its receiver type.
type funcKey = string

type site struct {
	code   string
	status int
	pos    token.Position
}

type scan struct {
	fset  *token.FileSet
	files []*ast.File

	// consts maps a package-level identifier to its string value. It is what
	// resolves CodeNotInstalled, ApprovalRateLimitedCode and SurfaceConsole
	// without a type checker.
	consts map[string]string

	// errorBodies names the response types that carry a code in a field the
	// wire calls `error`. ErrorResponse is the one writeError builds; the
	// others are the surfaces that answer with a body of their own shape and
	// put a code in it anyway, which is how "count the writeError call sites"
	// silently misses a code (it missed `invalid_policy`).
	errorBodies map[string]bool
	// handledBodies are the error-body literals the scan read. Anything of
	// those types written anywhere else is reported rather than skipped.
	handledBodies map[token.Pos]bool

	// bodies holds every function the scanner walks, including the literals.
	bodies map[funcKey]*ast.BlockStmt
	// receivers maps a method's key to its receiver identifier, so that a
	// x.helper() call inside it resolves to Type.helper.
	receivers map[funcKey]string
	// tables holds the subset whose results are (int, string, string): the
	// error tables whose codes never appear at a writeError call site.
	tables map[funcKey]bool

	calls map[funcKey]map[funcKey]bool
	// roots maps a mounted handler to the listener it is mounted on.
	roots map[funcKey]map[string]bool

	sites map[funcKey][]site
	// forwarders are writeError call sites whose code is a value rather than a
	// literal. They emit nothing themselves; the table they read from does.
	forwarders map[funcKey][]token.Position

	problems []string
}

func (s *scan) reportf(pos token.Position, format string, args ...any) {
	s.problems = append(s.problems, fmt.Sprintf("%s: %s", pos, fmt.Sprintf(format, args...)))
}

// newScan parses the package's non-test sources and builds everything the
// rendering needs.
func newScan(dir string) (*scan, error) {
	s := &scan{
		fset:          token.NewFileSet(),
		consts:        map[string]string{},
		errorBodies:   map[string]bool{},
		handledBodies: map[token.Pos]bool{},
		bodies:        map[funcKey]*ast.BlockStmt{},
		receivers:     map[funcKey]string{},
		tables:        map[funcKey]bool{},
		calls:         map[funcKey]map[funcKey]bool{},
		roots:         map[funcKey]map[string]bool{},
		sites:         map[funcKey][]site{},
		forwarders:    map[funcKey][]token.Position{},
	}

	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", dir, err)
	}
	var files []*ast.File
	for _, e := range entries {
		name := e.Name()
		if e.IsDir() || !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") {
			continue
		}
		f, perr := parser.ParseFile(s.fset, filepath.Join(dir, name), nil, parser.SkipObjectResolution)
		if perr != nil {
			return nil, fmt.Errorf("parse %s: %w", name, perr)
		}
		files = append(files, f)
	}
	if len(files) == 0 {
		return nil, fmt.Errorf("%s holds no non-test Go files", dir)
	}
	s.files = files

	for _, f := range files {
		s.collectConsts(f)
		s.collectErrorBodies(f)
	}
	for _, f := range files {
		s.collectFuncs(f)
	}
	for _, f := range files {
		s.collectRoots(f)
	}
	for key, body := range s.bodies {
		s.walkBody(key, body)
	}
	return s, nil
}

func (s *scan) collectConsts(f *ast.File) {
	for _, decl := range f.Decls {
		gen, ok := decl.(*ast.GenDecl)
		if !ok || gen.Tok != token.CONST {
			continue
		}
		for _, spec := range gen.Specs {
			vs, ok := spec.(*ast.ValueSpec)
			if !ok {
				continue
			}
			for i, name := range vs.Names {
				if i >= len(vs.Values) {
					continue
				}
				if lit, ok := vs.Values[i].(*ast.BasicLit); ok && lit.Kind == token.STRING {
					if v, uerr := strconv.Unquote(lit.Value); uerr == nil {
						s.consts[name.Name] = v
					}
				}
			}
		}
	}
}

// collectErrorBodies finds the response types that carry a code in an `error`
// field.
//
// The type is found by its JSON tag rather than by a list of names, and the
// reason is the bug this method was added for. The first version of this
// scanner read writeError call sites and the error tables, and asserted that
// [ErrorResponse] was the only body built outside writeError — which was true,
// and beside the point. `invalid_policy` goes out at 400 inside a
// [DiagnosticsResponse], whose `error` field is the same field on the wire and
// a different Go type in here. The console's own set said the server emits it;
// the artifact did not. A generator that renders less than the truth is exactly
// what every tripwire in this file is aimed at, and it took a hand-written
// assumption to slip one past them.
func (s *scan) collectErrorBodies(f *ast.File) {
	for _, decl := range f.Decls {
		gen, ok := decl.(*ast.GenDecl)
		if !ok || gen.Tok != token.TYPE {
			continue
		}
		for _, spec := range gen.Specs {
			ts, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}
			st, ok := ts.Type.(*ast.StructType)
			if !ok || st.Fields == nil {
				continue
			}
			for _, field := range st.Fields.List {
				if id, ok := field.Type.(*ast.Ident); !ok || id.Name != "string" {
					continue
				}
				if field.Tag == nil {
					continue
				}
				tag, err := strconv.Unquote(field.Tag.Value)
				if err != nil {
					continue
				}
				if strings.Contains(tag, `json:"error"`) || strings.Contains(tag, `json:"error,`) {
					s.errorBodies[ts.Name.Name] = true
				}
			}
		}
	}
}

// collectFuncs registers every declared function and every function literal
// inside one, so that a handler written inline is walked like any other.
func (s *scan) collectFuncs(f *ast.File) {
	for _, decl := range f.Decls {
		fn, ok := decl.(*ast.FuncDecl)
		if !ok || fn.Body == nil {
			continue
		}
		key := declKey(fn)
		s.bodies[key] = fn.Body
		if recv := receiverName(fn); recv != "" {
			s.receivers[key] = recv
		}
		if isErrorTable(fn.Type) {
			s.tables[key] = true
		}
		s.registerLiterals(key, fn.Body)
	}
}

// registerLiterals gives every function literal under a body its own key, so a
// writeError inside a closure is attributed to the function that holds it.
func (s *scan) registerLiterals(owner funcKey, body ast.Node) {
	n := 0
	ast.Inspect(body, func(node ast.Node) bool {
		lit, ok := node.(*ast.FuncLit)
		if !ok {
			return true
		}
		n++
		key := fmt.Sprintf("%s$%d", owner, n)
		s.bodies[key] = lit.Body
		s.edge(owner, key)
		return true
	})
}

// declKey renders a declaration's key. A method takes its receiver's type name,
// pointer or not, because the two are one method set here.
func declKey(fn *ast.FuncDecl) funcKey {
	if fn.Recv == nil || len(fn.Recv.List) == 0 {
		return fn.Name.Name
	}
	return typeName(fn.Recv.List[0].Type) + "." + fn.Name.Name
}

func typeName(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.StarExpr:
		return typeName(t.X)
	case *ast.Ident:
		return t.Name
	case *ast.IndexExpr:
		return typeName(t.X)
	}
	return ""
}

// isErrorTable reports whether a signature is one of the (status int, code,
// message string) tables. It is matched on the shape rather than on a name
// list, so a fifth table added tomorrow is scanned without this file changing.
func isErrorTable(ft *ast.FuncType) bool {
	if ft.Results == nil {
		return false
	}
	var kinds []string
	for _, field := range ft.Results.List {
		id, ok := field.Type.(*ast.Ident)
		if !ok {
			return false
		}
		n := len(field.Names)
		if n == 0 {
			n = 1
		}
		for i := 0; i < n; i++ {
			kinds = append(kinds, id.Name)
		}
	}
	return len(kinds) == 3 && kinds[0] == "int" && kinds[1] == "string" && kinds[2] == "string"
}

func (s *scan) edge(from, to funcKey) {
	if s.calls[from] == nil {
		s.calls[from] = map[funcKey]bool{}
	}
	s.calls[from][to] = true
}

// collectRoots reads the Routes() methods and records which listener each
// mounted handler answers on.
//
// A route's Handler is not always a bare method value — the console wraps its
// handlers in a header middleware, and one is an inline literal — so the whole
// Handler expression is walked and everything function-shaped in it becomes a
// root. Missing a wrapper would only lose surfaces, and a lost surface is a
// code that looks unreachable, which the reachability tripwire below turns into
// a failure rather than a quiet hole.
func (s *scan) collectRoots(f *ast.File) {
	for _, decl := range f.Decls {
		fn, ok := decl.(*ast.FuncDecl)
		if !ok || fn.Name.Name != "Routes" || fn.Recv == nil || fn.Body == nil {
			continue
		}
		recv := receiverName(fn)
		self := typeName(fn.Recv.List[0].Type)
		owner := declKey(fn)
		// registerLiterals numbered every function literal in this body in
		// source order; the counter here walks the same order, so an inline
		// handler is matched to the body that was registered for it.
		literals := 0

		ast.Inspect(fn.Body, func(node ast.Node) bool {
			// The literal is written `[]Route{{…}, {…}}`, so the elements
			// carry no type of their own: the slice's element type is what
			// identifies them. Matching the elements directly would find
			// nothing, which is how a scanner ends up attributing every code
			// to no surface at all.
			slice, ok := node.(*ast.CompositeLit)
			if !ok {
				return true
			}
			arr, ok := slice.Type.(*ast.ArrayType)
			if !ok {
				return true
			}
			if name, ok := arr.Elt.(*ast.Ident); !ok || name.Name != "Route" {
				return true
			}
			for _, elt := range slice.Elts {
				route, ok := elt.(*ast.CompositeLit)
				if !ok {
					s.reportf(s.fset.Position(elt.Pos()),
						"a Routes() element is not a literal this scanner can read")
					continue
				}
				s.collectRoute(owner, recv, self, route, &literals)
			}
			return false
		})
	}
}

// collectRoute reads one Route literal: which listener it is on, and what
// function answers it.
func (s *scan) collectRoute(owner funcKey, recv, self string, cl *ast.CompositeLit, literals *int) {
	surface, handler := "", ast.Expr(nil)
	routeName := ""
	for _, elt := range cl.Elts {
		kv, ok := elt.(*ast.KeyValueExpr)
		if !ok {
			continue
		}
		key, ok := kv.Key.(*ast.Ident)
		if !ok {
			continue
		}
		switch key.Name {
		case "Surface":
			surface = s.resolveString(kv.Value)
		case "Handler":
			handler = kv.Value
		case "Name":
			routeName = s.resolveString(kv.Value)
		}
	}
	pos := s.fset.Position(cl.Pos())
	if surface == "" {
		s.reportf(pos, "route %q declares a Surface this scanner cannot resolve", routeName)
		return
	}
	if handler == nil {
		s.reportf(pos, "route %q declares no Handler", routeName)
		return
	}
	found := s.handlerRoots(owner, recv, self, handler, literals)
	if len(found) == 0 {
		s.reportf(pos, "route %q has a Handler shape this scanner cannot follow; "+
			"the codes it writes would be attributed to no surface", routeName)
	}
	for _, key := range found {
		if s.roots[key] == nil {
			s.roots[key] = map[string]bool{}
		}
		s.roots[key][surface] = true
	}
}

// handlerRoots returns every function reachable *syntactically* from a Handler
// expression: the receiver's own methods named in it, the package functions
// named in it, and any literal written inline.
func (s *scan) handlerRoots(owner funcKey, recv, self string, handler ast.Expr, literals *int) []funcKey {
	var out []funcKey
	ast.Inspect(handler, func(node ast.Node) bool {
		switch n := node.(type) {
		case *ast.SelectorExpr:
			if id, ok := n.X.(*ast.Ident); ok && id.Name == recv {
				key := self + "." + n.Sel.Name
				if _, known := s.bodies[key]; known {
					out = append(out, key)
				}
			}
		case *ast.Ident:
			if _, known := s.bodies[n.Name]; known {
				out = append(out, n.Name)
			}
		case *ast.FuncLit:
			*literals++
			key := fmt.Sprintf("%s$%d", owner, *literals)
			if _, known := s.bodies[key]; known {
				out = append(out, key)
			}
		}
		return true
	})
	return out
}

func receiverName(fn *ast.FuncDecl) string {
	if fn.Recv == nil || len(fn.Recv.List) == 0 || len(fn.Recv.List[0].Names) == 0 {
		return ""
	}
	return fn.Recv.List[0].Names[0].Name
}

// walkBody records what one function calls and what it emits.
func (s *scan) walkBody(key funcKey, body *ast.BlockStmt) {
	self := ""
	if i := strings.Index(key, "."); i > 0 {
		self = key[:i]
	}
	recv := s.receiverOf(key)

	ast.Inspect(body, func(node ast.Node) bool {
		switch n := node.(type) {
		case *ast.FuncLit:
			// Registered and walked under its own key.
			return false
		case *ast.SelectorExpr:
			if id, ok := n.X.(*ast.Ident); ok && recv != "" && id.Name == recv {
				if callee := self + "." + n.Sel.Name; s.bodies[callee] != nil {
					s.edge(key, callee)
				}
			}
		case *ast.Ident:
			if s.bodies[n.Name] != nil {
				s.edge(key, n.Name)
			}
		case *ast.CallExpr:
			s.collectWriteError(key, n)
			s.collectWriteJSON(key, n)
		case *ast.ReturnStmt:
			if s.tables[key] {
				s.collectTableReturn(key, n)
			}
		}
		return true
	})
}

// receiverOf recovers the receiver identifier for a method key, so that a
// x.helper() call inside it resolves to Type.helper.
func (s *scan) receiverOf(key funcKey) string {
	// Function literals inherit their owner's receiver: `$N` is appended to the
	// owner's key, and the closure sees the same identifier.
	base := key
	if i := strings.Index(base, "$"); i > 0 {
		base = base[:i]
	}
	return s.receivers[base]
}

func (s *scan) collectWriteError(key funcKey, call *ast.CallExpr) {
	id, ok := call.Fun.(*ast.Ident)
	if !ok || id.Name != "writeError" || len(call.Args) != 4 {
		return
	}
	pos := s.fset.Position(call.Pos())
	code := s.resolveString(call.Args[2])
	if code == "" {
		// A forwarded (status, code, message). The table it came from is
		// reached from this same function, and that is where the codes are
		// read; recorded so the tripwire below can insist that is true.
		s.forwarders[key] = append(s.forwarders[key], pos)
		return
	}
	status, ok := s.resolveStatus(call.Args[1])
	if !ok {
		s.reportf(pos, "writeError writes %q under a status this scanner cannot resolve; "+
			"write the http.Status constant at the call site so the artifact can state it", code)
		return
	}
	s.sites[key] = append(s.sites[key], site{code: code, status: status, pos: pos})
}

// collectWriteJSON reads the surfaces that answer a refusal with a body of
// their own shape.
//
// The status is what separates a code from a field that merely shares its name.
// [DryRunResponse] carries `error` too, and it is a sentence out of the
// evaluation trace rather than a vocabulary term — but it goes out with a 200,
// because the dry run succeeded and the policy is what did not. So the rule is
// the status: an `error` field on a refusal is a code, an `error` field on a
// success is a payload. That is derived from the call site rather than from a
// list of exempt types, which is the difference between a rule and a memory.
func (s *scan) collectWriteJSON(key funcKey, call *ast.CallExpr) {
	id, ok := call.Fun.(*ast.Ident)
	if !ok || id.Name != "writeJSON" || len(call.Args) != 3 {
		return
	}
	body, ok := call.Args[2].(*ast.CompositeLit)
	if !ok {
		return
	}
	name, ok := body.Type.(*ast.Ident)
	if !ok || !s.errorBodies[name.Name] {
		return
	}
	s.handledBodies[body.Pos()] = true

	// writeError is the generic writer: its code is a parameter, and every one
	// of its call sites is already read.
	if key == "writeError" {
		return
	}

	pos := s.fset.Position(call.Pos())
	status, ok := s.resolveStatus(call.Args[1])
	if !ok {
		s.reportf(pos, "a %s is written under a status this scanner cannot resolve; "+
			"whether its `error` field is a code depends on that status", name.Name)
		return
	}
	if status < http.StatusBadRequest {
		// A success carrying an `error` field. Not a refusal, not a code.
		return
	}
	code := ""
	for _, elt := range body.Elts {
		kv, ok := elt.(*ast.KeyValueExpr)
		if !ok {
			continue
		}
		if k, ok := kv.Key.(*ast.Ident); ok && k.Name == "Error" {
			code = s.resolveString(kv.Value)
		}
	}
	if code == "" {
		s.reportf(pos, "a %s goes out with status %d and this scanner cannot read the code in it",
			name.Name, status)
		return
	}
	s.sites[key] = append(s.sites[key], site{code: code, status: status, pos: pos})
}

// strayBodies reports every error-carrying response literal the scan did not
// read.
//
// It is the assumption underneath collectWriteJSON, checked rather than
// believed: these bodies reach the wire through writeJSON, so one built
// anywhere else — returned from a helper, stored in a variable, encoded by
// hand — is a code no set knows about.
func (s *scan) strayBodies() []string {
	var problems []string
	for _, f := range s.files {
		ast.Inspect(f, func(node ast.Node) bool {
			cl, ok := node.(*ast.CompositeLit)
			if !ok {
				return true
			}
			name, ok := cl.Type.(*ast.Ident)
			if !ok || !s.errorBodies[name.Name] {
				return true
			}
			if s.handledBodies[cl.Pos()] {
				return true
			}
			problems = append(problems, fmt.Sprintf(
				"%s: a %s is built somewhere other than a writeJSON argument; the scan reads "+
					"those call sites, so the code in this one is in no artifact",
				s.fset.Position(cl.Pos()), name.Name))
			return true
		})
	}
	return problems
}

func (s *scan) collectTableReturn(key funcKey, ret *ast.ReturnStmt) {
	if len(ret.Results) != 3 {
		// `return other()` — the delegation is an edge, and the callee's own
		// returns are read there.
		return
	}
	pos := s.fset.Position(ret.Pos())
	code := s.resolveString(ret.Results[1])
	if code == "" {
		s.reportf(pos, "an error table returns a code this scanner cannot resolve")
		return
	}
	status, ok := s.resolveStatus(ret.Results[0])
	if !ok {
		s.reportf(pos, "an error table returns %q under a status this scanner cannot resolve", code)
		return
	}
	s.sites[key] = append(s.sites[key], site{code: code, status: status, pos: pos})
}

// resolveString returns a string literal's value, or a package constant's, or
// "" when the expression is neither.
func (s *scan) resolveString(expr ast.Expr) string {
	switch e := expr.(type) {
	case *ast.BasicLit:
		if e.Kind != token.STRING {
			return ""
		}
		v, err := strconv.Unquote(e.Value)
		if err != nil {
			return ""
		}
		return v
	case *ast.Ident:
		return s.consts[e.Name]
	}
	return ""
}

// resolveStatus reads an HTTP status out of the call site.
func (s *scan) resolveStatus(expr ast.Expr) (int, bool) {
	switch e := expr.(type) {
	case *ast.BasicLit:
		if e.Kind != token.INT {
			return 0, false
		}
		n, err := strconv.Atoi(e.Value)
		return n, err == nil
	case *ast.SelectorExpr:
		pkg, ok := e.X.(*ast.Ident)
		if !ok || pkg.Name != "http" {
			return 0, false
		}
		n, ok := httpStatusByName()[e.Sel.Name]
		return n, ok
	}
	return 0, false
}

// httpStatusByName inverts net/http's own status text table into the constant
// names the handlers write.
//
// It is derived rather than typed out for the same reason the code list is: a
// hand-written table of forty constants is a table that can be wrong, and the
// one thing worse than an unresolvable status is a status resolved to the wrong
// number. http.StatusText is the package's own data, and every constant except
// StatusTeapot (whose text is "I'm a teapot") is its text with the separators
// removed. StatusTeapot is not used here, and if it ever were, resolveStatus
// would fail loudly rather than guess.
func httpStatusByName() map[string]int {
	out := map[string]int{}
	replacer := strings.NewReplacer(" ", "", "-", "", "'", "")
	for n := 100; n < 600; n++ {
		text := http.StatusText(n)
		if text == "" {
			continue
		}
		out["Status"+replacer.Replace(text)] = n
	}
	return out
}

// ---------------------------------------------------------------------------
// attribution and rendering
// ---------------------------------------------------------------------------

// surfacesOf walks the call graph forward from every mounted handler and
// returns, for each function, the listeners it can be reached from.
func (s *scan) surfacesOf() map[funcKey]map[string]bool {
	out := map[funcKey]map[string]bool{}
	for root, surfaces := range s.roots {
		for surface := range surfaces {
			var visit func(funcKey)
			seen := map[funcKey]bool{}
			visit = func(key funcKey) {
				if seen[key] {
					return
				}
				seen[key] = true
				if out[key] == nil {
					out[key] = map[string]bool{}
				}
				out[key][surface] = true
				for callee := range s.calls[key] {
					visit(callee)
				}
			}
			visit(root)
		}
	}
	return out
}

// render turns the scan into the document, and reports every way the scan is
// not trustworthy enough to render.
//
// The tripwires are all one failure mode: a generator that quietly renders less
// than the truth. An artifact that is short is worse than no artifact, because
// the console check downstream would then read the shortfall as "the console
// branches on a code the server cannot emit" and blame the wrong side.
func (s *scan) render() (errorCodeDocument, []string) {
	problems := append([]string(nil), s.problems...)
	problems = append(problems, s.strayBodies()...)
	reach := s.surfacesOf()

	type acc struct {
		statuses map[int]bool
		surfaces map[string]bool
	}
	codes := map[string]*acc{}

	for key, sites := range s.sites {
		surfaces := reach[key]
		if len(surfaces) == 0 {
			for _, st := range sites {
				problems = append(problems, fmt.Sprintf(
					"%s: %q is written by %s, which no mounted route reaches; either the route "+
						"table changed shape or this scanner lost the call graph edge that leads here",
					st.pos, st.code, key))
			}
			continue
		}
		for _, st := range sites {
			a := codes[st.code]
			if a == nil {
				a = &acc{statuses: map[int]bool{}, surfaces: map[string]bool{}}
				codes[st.code] = a
			}
			a.statuses[st.status] = true
			for surface := range surfaces {
				a.surfaces[surface] = true
			}
		}
	}

	// A writeError whose code is a value has to sit in a function that reads
	// one of the tables. If it does not, a code is going out that nothing in
	// this file ever saw.
	for key, positions := range s.forwarders {
		if s.reachesTable(key) {
			continue
		}
		for _, pos := range positions {
			problems = append(problems, fmt.Sprintf(
				"%s: writeError is called with a computed code in %s, and %s reaches no "+
					"(status, code, message) table; that code is in no artifact", pos, key, key))
		}
	}

	if len(codes) == 0 {
		problems = append(problems, "the scan found no error codes at all, which cannot be true "+
			"of this package: the scanner is broken, not the handlers")
	}
	surfacesSeen := map[string]bool{}
	for _, a := range codes {
		for surface := range a.surfaces {
			surfacesSeen[surface] = true
		}
	}
	for _, surface := range api.Surfaces() {
		if !surfacesSeen[string(surface)] {
			problems = append(problems, fmt.Sprintf(
				"no error code is attributed to the %s listener; every surface this binary "+
					"binds can refuse something, so this is the scan losing a surface", surface))
		}
	}

	doc := errorCodeDocument{
		Version:  errorCodeDocumentVersion,
		Note:     errorCodeNote,
		Surfaces: sortedKeys(surfacesSeen),
		Codes:    make([]emittedCode, 0, len(codes)),
	}
	for code, a := range codes {
		statuses := make([]int, 0, len(a.statuses))
		for st := range a.statuses {
			statuses = append(statuses, st)
		}
		sort.Ints(statuses)
		doc.Codes = append(doc.Codes, emittedCode{
			Code:     code,
			Statuses: statuses,
			Surfaces: sortedKeys(a.surfaces),
		})
	}
	sort.Slice(doc.Codes, func(i, j int) bool { return doc.Codes[i].Code < doc.Codes[j].Code })
	sort.Strings(problems)
	return doc, problems
}

// reachesTable reports whether a function can reach one of the error tables.
func (s *scan) reachesTable(from funcKey) bool {
	seen := map[funcKey]bool{}
	var visit func(funcKey) bool
	visit = func(key funcKey) bool {
		if seen[key] {
			return false
		}
		seen[key] = true
		if s.tables[key] {
			return true
		}
		for callee := range s.calls[key] {
			if visit(callee) {
				return true
			}
		}
		return false
	}
	return visit(from)
}

func sortedKeys(m map[string]bool) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

func renderErrorCodes(doc errorCodeDocument) ([]byte, error) {
	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetIndent("", "  ")
	if err := enc.Encode(doc); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// ---------------------------------------------------------------------------
// the tests
// ---------------------------------------------------------------------------

// TestErrorCodeFileIsUpToDate keeps the rendered vocabulary and the handlers
// from drifting.
//
// It rewrites on mismatch and then fails, for the reason
// TestConsoleContractFileIsUpToDate does: the failure a contributor wants is
// "your new code is in the artifact, review the diff", not a transcription
// task. The rewrite is also the thing that makes the console check next door
// meaningful — a contributor who adds a code and commits the regenerated file
// is told, in the same pull request, whether the console handles it.
func TestErrorCodeFileIsUpToDate(t *testing.T) {
	s, err := newScan(".")
	if err != nil {
		t.Fatalf("scan internal/api: %v", err)
	}
	doc, problems := s.render()
	if len(problems) > 0 {
		t.Fatalf("the error code scan is not trustworthy enough to render:\n  %s",
			strings.Join(problems, "\n  "))
	}
	want, err := renderErrorCodes(doc)
	if err != nil {
		t.Fatalf("render the error codes: %v", err)
	}

	got, rerr := os.ReadFile(errorCodeFile)
	if rerr == nil && bytes.Equal(got, want) {
		return
	}
	if mkErr := os.MkdirAll(filepath.Dir(errorCodeFile), 0o750); mkErr != nil {
		t.Fatalf("create the contract directory: %v", mkErr)
	}
	if werr := os.WriteFile(errorCodeFile, want, 0o600); werr != nil {
		t.Fatalf("write the error codes: %v", werr)
	}
	t.Fatalf("%s was stale and has been rewritten; review the diff, commit it, and expect "+
		"console/scripts/check-contract.mjs to name any code the console does not handle "+
		"or branches on and can no longer receive", errorCodeFile)
}

// TestEveryErrorCodeCarryingBodyIsKnown states the emit surface the scan
// assumes, as a list a reader can check by eye.
//
// The scan finds these types by their JSON tag, which is right and also
// invisible: nothing in the rendering says which types it thought it was
// looking for. This names them. A new response body that carries a code — the
// pattern that hid `invalid_policy` from the first version of this file — turns
// up here as an unexpected name rather than as a silently shorter artifact, and
// a type that loses its `error` field turns up as a missing one.
func TestEveryErrorCodeCarryingBodyIsKnown(t *testing.T) {
	s, err := newScan(".")
	if err != nil {
		t.Fatalf("scan internal/api: %v", err)
	}
	// Every response type in this package with a string field the wire calls
	// `error`. DryRunResponse is on the list and contributes no code: its field
	// is a sentence from the evaluation trace and it goes out with a 200, which
	// is how the scan tells the two apart.
	want := map[string]bool{
		"ErrorResponse":           true,
		"DiagnosticsResponse":     true,
		"PendingRevisionResponse": true,
		"DryRunResponse":          true,
	}
	for name := range s.errorBodies {
		if !want[name] {
			t.Errorf("%s carries an `error` field and this test did not know about it; "+
				"confirm the scan reads the status it goes out under before adding it here", name)
		}
	}
	for name := range want {
		if !s.errorBodies[name] {
			t.Errorf("%s no longer carries an `error` field; if it stopped answering refusals, "+
				"take it off this list", name)
		}
	}
}

// TestTheErrorCodeScannerFindsWhatItIsAimedAt is the self-check.
//
// A scanner that has only ever been run on a tree it agrees with is not known
// to read anything. Each case below is one shape the real package uses, written
// out here so the resolution rules are pinned independently of whether
// internal/api happens to still contain an example of them.
func TestTheErrorCodeScannerFindsWhatItIsAimedAt(t *testing.T) {
	const source = `package api

import "net/http"

const CodeSpelledOut = "spelled_out"

type Surface string

const SurfaceConsole Surface = "console"

type Route struct {
	Name    string
	Surface Surface
	Handler any
}

type Widget struct{}

// A refusal with a body of its own shape, and a success that happens to carry
// an ` + "`error`" + ` field too. Only the first is a code.
type WidgetDiagnostics struct {
	Error string ` + "`" + `json:"error"` + "`" + `
}

type WidgetResult struct {
	Error string ` + "`" + `json:"error,omitempty"` + "`" + `
}

func (wg *Widget) Routes() []Route {
	return []Route{{Name: "widget", Surface: SurfaceConsole, Handler: http.HandlerFunc(wg.serve)}}
}

func (wg *Widget) serve(w http.ResponseWriter, r *http.Request) {
	writeError(w, http.StatusBadRequest, "literal_code", "a literal at the call site")
	writeError(w, http.StatusServiceUnavailable, CodeSpelledOut, "a package constant")
	status, code, message := widgetError(nil)
	writeError(w, status, code, message)
	writeJSON(w, http.StatusBadRequest, WidgetDiagnostics{Error: "shaped_body"})
	writeJSON(w, http.StatusOK, WidgetResult{Error: "not_a_code_because_it_succeeded"})
}

func writeJSON(w http.ResponseWriter, status int, body any) {}

func widgetError(err error) (status int, code, message string) {
	if err == nil {
		return http.StatusConflict, "from_a_table", "a code that is a value"
	}
	return noSuchWidget()
}

func noSuchWidget() (status int, code, message string) {
	return http.StatusNotFound, "delegated", "a code one table hands to another"
}

func writeError(w http.ResponseWriter, status int, code, message string) {}
`
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "widget.go"), []byte(source), 0o600); err != nil {
		t.Fatalf("write the fixture: %v", err)
	}
	s, err := newScan(dir)
	if err != nil {
		t.Fatalf("scan the fixture: %v", err)
	}
	doc, problems := s.render()
	// The fixture binds one listener, so the "every surface has a code"
	// tripwire fires on the two it does not bind. That tripwire is exercised in
	// internal/release against the real document; here it is expected noise.
	for _, p := range problems {
		if !strings.Contains(p, "no error code is attributed to the") {
			t.Errorf("the fixture scan reported %q, and the fixture is meant to be clean", p)
		}
	}

	want := map[string][]int{
		"literal_code": {http.StatusBadRequest},
		"spelled_out":  {http.StatusServiceUnavailable},
		"from_a_table": {http.StatusConflict},
		"delegated":    {http.StatusNotFound},
		"shaped_body":  {http.StatusBadRequest},
	}
	got := map[string][]int{}
	for _, c := range doc.Codes {
		got[c.Code] = c.Statuses
		if len(c.Surfaces) != 1 || c.Surfaces[0] != "console" {
			t.Errorf("%s reached surfaces %v, want [console]: the call graph lost the route",
				c.Code, c.Surfaces)
		}
	}
	for code, statuses := range want {
		if fmt.Sprint(got[code]) != fmt.Sprint(statuses) {
			t.Errorf("%s = %v, want %v", code, got[code], statuses)
		}
	}
	for code := range got {
		if _, ok := want[code]; !ok {
			t.Errorf("the scan invented %q", code)
		}
	}
}

// TestTheErrorCodeScannerRefusesWhatItCannotRead is the other half of the
// self-check: the scanner has to fail rather than render short.
//
// Both fixtures are a hole the scanner could paper over — a code no route
// reaches, and a code it cannot read at all — and both are the failure mode the
// tripwires exist for.
func TestTheErrorCodeScannerRefusesWhatItCannotRead(t *testing.T) {
	const preamble = `package api

import "net/http"

type Surface string

const SurfaceConsole Surface = "console"

type Route struct {
	Name    string
	Surface Surface
	Handler any
}

type Widget struct{}

func (wg *Widget) Routes() []Route {
	return []Route{{Name: "widget", Surface: SurfaceConsole, Handler: http.HandlerFunc(wg.serve)}}
}

func writeError(w http.ResponseWriter, status int, code, message string) {}
`
	cases := map[string]struct {
		body string
		want string
	}{
		"a code written from a function no route reaches": {
			body: `
func (wg *Widget) serve(w http.ResponseWriter, r *http.Request) {}

func (wg *Widget) orphan(w http.ResponseWriter) {
	writeError(w, http.StatusBadRequest, "orphaned", "nothing mounts the handler that writes this")
}
`,
			want: "which no mounted route reaches",
		},
		"a code the scanner cannot resolve": {
			body: `
var spelling = "computed"

func (wg *Widget) serve(w http.ResponseWriter, r *http.Request) {
	writeError(w, http.StatusBadRequest, spelling, "a code that is a variable")
}
`,
			want: "reaches no (status, code, message) table",
		},
		// The shape that got past the first version of this scanner: a code in
		// a response body of its own type. Here it never reaches a writeJSON
		// argument, so the scan has no status to judge it by and no call site
		// to read it from.
		"an error body built somewhere the scan does not read": {
			body: `
type WidgetDiagnostics struct {
	Error string ` + "`" + `json:"error"` + "`" + `
}

func (wg *Widget) serve(w http.ResponseWriter, r *http.Request) {
	body := WidgetDiagnostics{Error: "smuggled"}
	_ = body
}
`,
			want: "is built somewhere other than a writeJSON argument",
		},
	}
	for name, tc := range cases {
		t.Run(name, func(t *testing.T) {
			dir := t.TempDir()
			if err := os.WriteFile(filepath.Join(dir, "widget.go"), []byte(preamble+tc.body), 0o600); err != nil {
				t.Fatalf("write the fixture: %v", err)
			}
			s, err := newScan(dir)
			if err != nil {
				t.Fatalf("scan the fixture: %v", err)
			}
			_, problems := s.render()
			if !strings.Contains(strings.Join(problems, "\n"), tc.want) {
				t.Errorf("the scan reported %v, want something containing %q", problems, tc.want)
			}
		})
	}
}
