#!/usr/bin/env bash
#
# scripts/quickstart.sh — bring the demo bundle up and drive it end to end.
#
# This script is the canonical procedure. docs/quickstart.md explains what it
# does and why; it does not restate the steps, because two copies of a procedure
# drift and the copy nobody runs is the one that rots. Everything below is
# executed by CI on both demo profiles on every pull request, which is the only
# thing that keeps the documentation and the product in the same universe.
#
# Requirements: docker (with compose v2), curl, jq, openssl. No Go toolchain —
# the stamp CLI is invoked inside the image, which is also how an operator who
# has only the container would do it.
#
# Usage:
#   scripts/quickstart.sh                  # default profile (no broker)
#   scripts/quickstart.sh --profile kafka  # Kafka ingestion overlay
#   scripts/quickstart.sh --keep           # leave the stack running afterwards
#   scripts/quickstart.sh --no-fresh       # reuse whatever is already up

set -euo pipefail

# ---------------------------------------------------------------------------
# arguments and layout
# ---------------------------------------------------------------------------

PROFILE=default
KEEP=0
FRESH=1

while [ $# -gt 0 ]; do
  case "$1" in
    --profile) PROFILE="${2:-}"; shift 2 ;;
    --profile=*) PROFILE="${1#*=}"; shift ;;
    --keep) KEEP=1; shift ;;
    --no-fresh) FRESH=0; shift ;;
    -h|--help)
      sed -n '2,22p' "$0" | sed 's/^# \{0,1\}//'
      exit 0 ;;
    *) echo "quickstart: unknown argument $1" >&2; exit 2 ;;
  esac
done

case "$PROFILE" in
  default|kafka) ;;
  *) echo "quickstart: --profile must be 'default' or 'kafka', got '$PROFILE'" >&2; exit 2 ;;
esac

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEMO_DIR="$REPO_ROOT/deploy/demo"
RUN_DIR="$DEMO_DIR/.run"
ENV_FILE="$DEMO_DIR/.env"

COMPOSE=(docker compose -f "$DEMO_DIR/docker-compose.yml")
if [ "$PROFILE" = kafka ]; then
  COMPOSE+=(-f "$DEMO_DIR/docker-compose.kafka.yml")
fi

START_EPOCH=$SECONDS
TIMINGS=()

# ---------------------------------------------------------------------------
# output
# ---------------------------------------------------------------------------

if [ -t 1 ]; then BOLD=$'\033[1m'; DIM=$'\033[2m'; RED=$'\033[31m'; GREEN=$'\033[32m'; OFF=$'\033[0m'
else BOLD=; DIM=; RED=; GREEN=; OFF=; fi

STEP=0
step() {
  STEP=$((STEP + 1))
  printf '\n%s[%2d] %s%s %s(+%ds)%s\n' "$BOLD" "$STEP" "$1" "$OFF" "$DIM" "$((SECONDS - START_EPOCH))" "$OFF"
}
note() { printf '     %s\n' "$1"; }
ok()   { printf '     %s✓%s %s\n' "$GREEN" "$OFF" "$1"; }
mark() { TIMINGS+=("$((SECONDS - START_EPOCH))s  $1"); }
die()  { printf '\n%squickstart failed:%s %s\n' "$RED" "$OFF" "$1" >&2; exit 1; }

# assert_eq WANT GOT WHAT
assert_eq() {
  if [ "$1" != "$2" ]; then
    die "$3: wanted '$1', got '$2'"
  fi
  ok "$3 = $2"
}

cleanup() {
  local rc=$?
  if [ "$rc" -ne 0 ]; then
    printf '\n%s--- stamp logs (tail) ---%s\n' "$DIM" "$OFF" >&2
    "${COMPOSE[@]}" logs --tail 60 stamp >&2 2>/dev/null || true
  fi
  if [ "$KEEP" -eq 0 ]; then
    "${COMPOSE[@]}" down -v --remove-orphans >/dev/null 2>&1 || true
  fi
  exit $rc
}

# ---------------------------------------------------------------------------
# 1. preflight
# ---------------------------------------------------------------------------

step "checking the tools this script needs"
for tool in docker curl jq openssl; do
  command -v "$tool" >/dev/null 2>&1 || die "$tool is not on PATH"
done
docker compose version >/dev/null 2>&1 || die "docker compose v2 is not available"
ok "docker, docker compose, curl, jq, openssl"

# ---------------------------------------------------------------------------
# 2. credentials
#
# The demo ships no credentials. They are generated here, into a file that is
# not tracked, so that there is no demo credential in the repository for a
# non-demo deployment to be started with — which is how this bundle answers R42
# without inventing a runtime "profile" flag. See docs/security.md.
# ---------------------------------------------------------------------------

step "generating this installation's demo credentials"
mkdir -p "$RUN_DIR"
if [ -f "$ENV_FILE" ]; then
  ok "reusing $ENV_FILE (delete it to rotate)"
else
  secret() { openssl rand -hex 24; }
  umask 077
  cat >"$ENV_FILE" <<EOF
# Generated by scripts/quickstart.sh. Not tracked, not shared, not a template.
# Delete this file to rotate every credential in the demo.
DEMO_POSTGRES_PASSWORD=$(secret)
DEMO_KEYCLOAK_ADMIN_PASSWORD=$(secret)
DEMO_USER_PASSWORD=$(secret)
DEMO_PEP_CLIENT_SECRET=$(secret)
DEMO_INGEST_CLIENT_SECRET=$(secret)
EOF
  ok "wrote $ENV_FILE with fresh random values"
fi
set -a
# shellcheck disable=SC1090  # generated above; there is nothing to follow
. "$ENV_FILE"
set +a

KEYCLOAK_PORT="${DEMO_KEYCLOAK_PORT:-18780}"
PEP_PORT="${DEMO_PEP_PORT:-18781}"
CONSOLE_PORT="${DEMO_CONSOLE_PORT:-18782}"
CALLBACK_PORT="${DEMO_CALLBACK_PORT:-18783}"

KC="http://localhost:$KEYCLOAK_PORT/realms/stamp-demo"
PEP="http://localhost:$PEP_PORT"
CONSOLE="http://localhost:$CONSOLE_PORT"
CALLBACK="http://localhost:$CALLBACK_PORT"

# ---------------------------------------------------------------------------
# 3. bring the stack up
# ---------------------------------------------------------------------------

trap cleanup EXIT

step "starting the demo stack (profile: $PROFILE)"
if [ "$FRESH" -eq 1 ]; then
  note "removing any previous demo stack and its volumes"
  "${COMPOSE[@]}" down -v --remove-orphans >/dev/null 2>&1 || true
fi
# The dependency graph does the sequencing: `stamp` waits on the two healthy
# services and on the one-shot that generates the checkpoint key. `--wait` is
# asked only of the long-running pair, because it reads a one-shot's clean exit
# as a failure.
"${COMPOSE[@]}" up -d --build --wait --wait-timeout 300 postgres keycloak >/dev/null
"${COMPOSE[@]}" up -d --build stamp >/dev/null
mark "containers started"

step "waiting for the surfaces to answer"
wait_for() {
  local url=$1 what=$2 i
  for i in $(seq 1 120); do
    if curl -fsS -o /dev/null "$url" 2>/dev/null; then
      ok "$what after ${i}s"
      return 0
    fi
    sleep 1
  done
  die "$what never answered ($url)"
}
wait_for "$KC/.well-known/openid-configuration" "the demo IdP is serving the stamp-demo realm"
wait_for "$PEP/healthz" "the PEP surface"
wait_for "$CONSOLE/healthz" "the console surface"
wait_for "$CALLBACK/healthz" "the callback surface"
mark "surfaces healthy"

# ---------------------------------------------------------------------------
# 4. credentials from the demo IdP
# ---------------------------------------------------------------------------

step "getting credentials from the demo IdP"

# A workload credential: client credentials, the grant a PEP holds.
client_token() {
  local id=$1 secret=$2 body
  body=$(curl -fsS -X POST "$KC/protocol/openid-connect/token" \
    -d grant_type=client_credentials -d "client_id=$id" -d "client_secret=$secret") \
    || die "the IdP refused client credentials for $id"
  printf '%s' "$body" | jq -er .access_token
}

# An end-user credential: authorization code with PKCE, driven the way the
# console's browser drives it. Nothing here is a shortcut past the login form —
# the point is that the realm the console is pointed at really does log these
# users in, with these redirect URIs and this challenge method.
user_token() {
  local user=$1 client=$2 redirect=$3
  local jar page action verifier challenge location code body
  jar="$RUN_DIR/cookies-$user.txt"; : >"$jar"
  verifier=$(openssl rand -hex 40)
  challenge=$(printf '%s' "$verifier" | openssl dgst -binary -sha256 \
    | openssl base64 | tr '+/' '-_' | tr -d '=\n')

  page=$(curl -fsS -c "$jar" -G "$KC/protocol/openid-connect/auth" \
    --data-urlencode "client_id=$client" \
    --data-urlencode "response_type=code" \
    --data-urlencode "scope=openid" \
    --data-urlencode "redirect_uri=$redirect" \
    --data-urlencode "state=quickstart-$user" \
    --data-urlencode "code_challenge=$challenge" \
    --data-urlencode "code_challenge_method=S256") \
    || die "the IdP would not serve a login page for $client"

  action=$(printf '%s' "$page" | tr '>' '>\n' | sed -n 's/.*action="\([^"]*\)".*/\1/p' | head -1)
  [ -n "$action" ] || die "no login form in the IdP's response for $user"
  action=${action//&amp;/&}

  location=$(curl -sS -b "$jar" -c "$jar" -o /dev/null -D - \
    --data-urlencode "username=$user" \
    --data-urlencode "password=$DEMO_USER_PASSWORD" \
    --data-urlencode "credentialId=" \
    "$action" | tr -d '\r' | sed -n 's/^[Ll]ocation: //p' | head -1)
  case "$location" in
    *code=*) ;;
    *) die "the login form did not return an authorization code for $user (redirect: ${location:-none})" ;;
  esac
  code=${location#*code=}; code=${code%%&*}

  body=$(curl -fsS -X POST "$KC/protocol/openid-connect/token" \
    -d grant_type=authorization_code -d "client_id=$client" \
    --data-urlencode "redirect_uri=$redirect" \
    --data-urlencode "code=$code" --data-urlencode "code_verifier=$verifier") \
    || die "the token endpoint refused the authorization code for $user"
  printf '%s' "$body" | jq -er .access_token
}

PEP_TOKEN=$(client_token stamp-pep "$DEMO_PEP_CLIENT_SECRET")
INGEST_TOKEN=$(client_token stamp-ingest "$DEMO_INGEST_CLIENT_SECRET")
ok "workload credentials for stamp-pep and stamp-ingest"

CONSOLE_REDIRECT="$CONSOLE/console/callback"
ANN_TOKEN=$(user_token ann stamp-console "$CONSOLE_REDIRECT")
BOB_TOKEN=$(user_token bob stamp-console "$CONSOLE_REDIRECT")
CID_TOKEN=$(user_token cid stamp-console "$CONSOLE_REDIRECT")
ok "ann, bob and cid logged in through the demo IdP with the console's own client and PKCE"
mark "credentials obtained"

# ---------------------------------------------------------------------------
# 5. the bootstrap token, and loading the example policies from files
# ---------------------------------------------------------------------------

step "reading the one-time governance bootstrap token"
BOOTSTRAP=""
for _ in $(seq 1 60); do
  # It is printed to stdout exactly once, on the first start with the api role,
  # and stored only as a digest. Reading it out of the container's log is the
  # demo's stand-in for an operator reading it off their terminal.
  BOOTSTRAP=$("${COMPOSE[@]}" logs --no-color --no-log-prefix stamp 2>/dev/null \
    | awk '/governance bootstrap token/ {grab=1; next} grab && NF {print $1; exit}')
  [ -n "$BOOTSTRAP" ] && break
  sleep 1
done
[ -n "$BOOTSTRAP" ] || die "the process never printed a bootstrap token"
ok "captured (${#BOOTSTRAP} characters, printed once and stored only as a digest)"

# The CLI runs inside the image. Tokens go through the environment rather than
# argv so that nothing puts a credential where a process listing would show it.
stamp_cli() {
  "${COMPOSE[@]}" exec -T \
    -e STAMP_API=http://127.0.0.1:8081 \
    -e STAMP_TOKEN="$ANN_TOKEN" \
    -e STAMP_BOOTSTRAP_TOKEN="$BOOTSTRAP" \
    stamp /stamp "$@"
}

step "loading the example policies from deploy/demo/policies with the file path"
stamp_cli policy apply --dir /demo/policies --wait --timeout 60s
mark "example policy set in force"

# ---------------------------------------------------------------------------
# 6. check
# ---------------------------------------------------------------------------

check() {
  local subject=$1 amount=$2 destination=$3
  curl -fsS -X POST "$PEP/access/v1/evaluation" \
    -H "Authorization: Bearer $PEP_TOKEN" -H 'Content-Type: application/json' \
    -d "{\"subject\":{\"type\":\"user\",\"id\":\"$subject\"},
         \"resource\":{\"type\":\"transfer\",\"id\":\"tx-1\",
                       \"properties\":{\"amount\":$amount,\"destination\":\"$destination\"}},
         \"action\":{\"name\":\"execute\"}}"
}

# A revision in force is not yet the set every check replica is judging with:
# the check plane holds a snapshot and refreshes it on a timer. Waiting for the
# answer rather than asserting it immediately is what a caller of a scaled-out
# deployment has to do too.
await_check() {
  local field=$1 want=$2 subject=$3 amount=$4 destination=$5 i
  for i in $(seq 1 60); do
    RESP=$(check "$subject" "$amount" "$destination")
    [ "$(printf '%s' "$RESP" | jq -r "$field")" = "$want" ] && return 0
    sleep 1
  done
  return 1
}

step "a check: the stateless, AuthZEN-compatible path"
await_check '.decision' true dana 500 domestic \
  || die "the example policy set never reached the check plane"
RESP=$(check dana 500 domestic)
assert_eq true "$(printf '%s' "$RESP" | jq -r .decision)" "check(dana, 500 domestic) decision"
assert_eq routine-transfer "$(printf '%s' "$RESP" | jq -r '.context["stamp.policy_id"]')" "policy that answered"
mark "check succeeded"

note "the same request against a policy that carries a challenge is a deny:"
RESP=$(check dana 25000 domestic)
assert_eq false "$(printf '%s' "$RESP" | jq -r .decision)" "check(dana, 25000 domestic) decision"
assert_eq requires_decision "$(printf '%s' "$RESP" | jq -r '.context["stamp.reason"]')" "reason"

# ---------------------------------------------------------------------------
# 7. decide, with an approval
# ---------------------------------------------------------------------------

step "a decide: the same policy set, with a quorum challenge collected"
DECISION=$(curl -fsS -X POST "$PEP/decisions" \
  -H "Authorization: Bearer $PEP_TOKEN" -H 'Content-Type: application/json' \
  -d '{"subject":{"type":"user","id":"dana"},
       "resource":{"type":"transfer","id":"tx-2","properties":{"amount":25000,"destination":"domestic"}},
       "action":{"name":"execute"},"ttl":"30m"}')
DECISION_ID=$(printf '%s' "$DECISION" | jq -er .id)
assert_eq pending "$(printf '%s' "$DECISION" | jq -r .state)" "decision state on creation"
assert_eq quorum "$(printf '%s' "$DECISION" | jq -r '.challenges[0].kind')" "challenge kind"
assert_eq 2 "$(printf '%s' "$DECISION" | jq -r '.challenges[0].need')" "approvals needed"

note "it is in bob's approval inbox:"
INBOX=$(curl -fsS "$CONSOLE/decisions/inbox" -H "Authorization: Bearer $BOB_TOKEN")
assert_eq 1 "$(printf '%s' "$INBOX" | jq -r --arg id "$DECISION_ID" '[.items[]|select(.decision_id==$id)]|length')" \
  "inbox entries for this decision"

# The review carries the binding hash the approval is tied to (R31). Echoing it
# back is what makes an approval an approval of the delta the approver saw, and
# not of whatever the delta became afterwards.
approve() {
  local id=$1 token=$2 review hash
  review=$(curl -fsS "$CONSOLE/decisions/$id/challenges/0/approval" -H "Authorization: Bearer $token")
  hash=$(printf '%s' "$review" | jq -r '.binding_hash // ""')
  curl -fsS -X POST "$CONSOLE/decisions/$id/challenges/0/approvals" \
    -H "Authorization: Bearer $token" -H 'Content-Type: application/json' \
    -d "{\"verdict\":\"approve\",\"binding_hash\":\"$hash\"}"
}
RESP=$(approve "$DECISION_ID" "$BOB_TOKEN")
assert_eq pending "$(printf '%s' "$RESP" | jq -r .state)" "state after one approval"
RESP=$(approve "$DECISION_ID" "$CID_TOKEN")
assert_eq allowed "$(printf '%s' "$RESP" | jq -r .state)" "state after the quorum is met"

note "and the creating PEP sees the resolution:"
RESP=$(curl -fsS "$PEP/decisions/$DECISION_ID" -H "Authorization: Bearer $PEP_TOKEN")
assert_eq allowed "$(printf '%s' "$RESP" | jq -r .state)" "decision read by its creator"
mark "decide with approval succeeded"

# ---------------------------------------------------------------------------
# 8. velocity
# ---------------------------------------------------------------------------

step "a velocity deny, fed through the $PROFILE profile's ingestion adapter"
now_rfc3339() { date -u +%Y-%m-%dT%H:%M:%SZ; }
EVENT_TIME=$(now_rfc3339)

if [ "$PROFILE" = kafka ]; then
  note "producing to the stamp.transfers topic"
  for n in 1 2 3; do
    printf '{"event_id":"qs-%s","subject":"dana","value":25000,"produced_at":"%s"}\n' "$n" "$EVENT_TIME"
  done | "${COMPOSE[@]}" exec -T kafka \
    /opt/kafka/bin/kafka-console-producer.sh --bootstrap-server localhost:9092 --topic stamp.transfers
  ok "3 events of 25,000 produced onto the topic"
  note "nothing is sent over HTTP in this profile: the deny below is the broker's alone"
else
  RESP=$(curl -fsS -X POST "$CALLBACK/ingest/v1/events" \
    -H "Authorization: Bearer $INGEST_TOKEN" -H 'Content-Type: application/json' \
    -d "{\"source\":\"transferred_today\",\"events\":[
          {\"event_id\":\"qs-1\",\"subject\":\"dana\",\"value\":25000,\"produced_at\":\"$EVENT_TIME\"},
          {\"event_id\":\"qs-2\",\"subject\":\"dana\",\"value\":25000,\"produced_at\":\"$EVENT_TIME\"},
          {\"event_id\":\"qs-3\",\"subject\":\"dana\",\"value\":25000,\"produced_at\":\"$EVENT_TIME\"}]}")
  assert_eq 3 "$(printf '%s' "$RESP" | jq -r .accepted)" "events accepted over HTTP ingest"
fi

note "waiting for the aggregate to carry 75,000 against a ceiling of 50,000"
await_check '.decision' false dana 500 domestic || die "the velocity limit never closed"
# The deny carries a reason and no policy identifier, and that is correct: no
# policy allowed this request, so there is none to name. `condition_not_met` is
# the same answer the amount test would have produced — the velocity limit is
# not a separate mechanism bolted beside the policy, it is a term in it.
assert_eq condition_not_met "$(printf '%s' "$RESP" | jq -r '.context["stamp.reason"]')" "velocity deny reason"
mark "velocity deny succeeded ($PROFILE profile)"

# ---------------------------------------------------------------------------
# 9. delegated MFA
# ---------------------------------------------------------------------------

step "a delegated MFA challenge (step-up redirect, D26)"
MFA_DECISION=$(curl -fsS -X POST "$PEP/decisions" \
  -H "Authorization: Bearer $PEP_TOKEN" -H 'Content-Type: application/json' \
  -d '{"subject":{"type":"user","id":"dana"},
       "resource":{"type":"ledger","id":"gl-2026"},
       "action":{"name":"export"},"ttl":"30m"}')
MFA_ID=$(printf '%s' "$MFA_DECISION" | jq -er .id)
assert_eq pending "$(printf '%s' "$MFA_DECISION" | jq -r .state)" "MFA decision state"
assert_eq mfa "$(printf '%s' "$MFA_DECISION" | jq -r '.challenges[0].kind')" "challenge kind"

note "the callback surface is live and refuses a forged completion:"
STATUS=$(curl -sS -o /dev/null -w '%{http_code}' -X POST "$CALLBACK/decisions/$MFA_ID/challenges/0/mfa" \
  -H 'Content-Type: application/json' \
  -d '{"correlator":"not-the-one","id_token":"not.a.token"}')
assert_eq 401 "$STATUS" "a completion with an unverifiable credential"

note "KNOWN GAP: the browser round trip that would satisfy this challenge cannot be"
note "driven from here. The step-up authorization URL is built at issuance and stored"
note "in the challenge detail, and no HTTP response carries it — see deploy/demo/README.md."

# ---------------------------------------------------------------------------
# 10. locking governance
# ---------------------------------------------------------------------------

step "locking governance so that this installation has no solo administrator"
stamp_cli policy lock --threshold 2 --approvers ann,bob,cid --yes
GOV=$(curl -fsS "$CONSOLE/governance" -H "Authorization: Bearer $ANN_TOKEN")
assert_eq quorum "$(printf '%s' "$GOV" | jq -r .mode)" "governance mode"
assert_eq true "$(printf '%s' "$GOV" | jq -r '.bootstrap.consumed')" "bootstrap token spent"
mark "governance locked"

# ---------------------------------------------------------------------------
# 11. M4: the authoring path, end to end
# ---------------------------------------------------------------------------

step "authoring a policy the way the console does, and taking it through approval"

# Both example transfer policies match this request on subject, resource and
# action; both exclude offshore in their condition. So the answer before the
# revision is a plain deny with no policy named, and after it the same request
# is a decision waiting on two approvers.
note "before the revision, an offshore transfer is denied outright:"
RESP=$(check dana 500 offshore)
assert_eq false "$(printf '%s' "$RESP" | jq -r .decision)" "check(dana, 500 offshore) before"
assert_eq condition_not_met "$(printf '%s' "$RESP" | jq -r '.context["stamp.reason"]')" "reason before"

OFFSHORE_DOC=$(cat <<'YAML'
apiVersion: stamp/v1
kind: Policy
id: offshore-transfer
description: Any transfer to an offshore destination needs two of the three named approvers.
subject: user
resource: transfer
actions:
  - execute
condition:
  left:
    field: resource.destination
  op: eq
  right: offshore
challenges:
  - type: quorum
    threshold: 2
    approvers:
      members:
        - ann
        - bob
        - cid
YAML
)

# This is the document the form builder produces: one change, `after` only. The
# `before` face is written by the server (D27) — a proposer who could state the
# past could write their own weakening classification.
REVISION_BODY=$(jq -n --arg after "$OFFSHORE_DOC" \
  '{delta: {changes: [{kind: "add", policy_id: "offshore-transfer", after: $after}]}}')

PREVIEW=$(curl -fsS -X POST "$CONSOLE/policies/revisions/preview" \
  -H "Authorization: Bearer $ANN_TOKEN" -H 'Content-Type: application/json' -d "$REVISION_BODY")
note "preview says: threshold $(printf '%s' "$PREVIEW" | jq -r .threshold), weakening=$(printf '%s' "$PREVIEW" | jq -r .weakening)"

PROPOSAL=$(curl -fsS -X POST "$CONSOLE/policies/revisions" \
  -H "Authorization: Bearer $ANN_TOKEN" -H 'Content-Type: application/json' -d "$REVISION_BODY")
REVISION_ID=$(printf '%s' "$PROPOSAL" | jq -er .id)
REV_DECISION=$(printf '%s' "$PROPOSAL" | jq -er .decision_id)
assert_eq pending "$(printf '%s' "$PROPOSAL" | jq -r .state)" "revision state on submission"
assert_eq form "$(printf '%s' "$PROPOSAL" | jq -r .origin)" "authoring origin"

note "the revision's own decision is in the approvers' inbox:"
INBOX=$(curl -fsS "$CONSOLE/decisions/inbox" -H "Authorization: Bearer $BOB_TOKEN")
assert_eq 1 "$(printf '%s' "$INBOX" | jq -r --arg id "$REV_DECISION" '[.items[]|select(.decision_id==$id)]|length')" \
  "inbox entries for the revision"

# The same call as the transfer approval above. A revision is governed by a
# decision, and the approval a governance quorum collects goes through the
# identical route with the identical binding hash — one pipeline, two authoring
# paths in front of it (D22).
approve "$REV_DECISION" "$BOB_TOKEN" >/dev/null
approve "$REV_DECISION" "$CID_TOKEN" >/dev/null

APPLIED=0
for _ in $(seq 1 90); do
  STATE=$(curl -fsS "$CONSOLE/policies/revisions/$REVISION_ID" -H "Authorization: Bearer $ANN_TOKEN" | jq -r .state)
  if [ "$STATE" = applied ]; then APPLIED=1; break; fi
  sleep 1
done
[ "$APPLIED" -eq 1 ] || die "the revision never took effect (last state: ${STATE:-unknown})"
ok "revision $REVISION_ID is in force"

note "and the answer changed, which is the only proof that matters:"
await_check '.context["stamp.reason"]' requires_decision dana 500 offshore \
  || die "the new policy never reached the check path"
assert_eq offshore-transfer "$(printf '%s' "$RESP" | jq -r '.context["stamp.policy_id"]')" "policy that answered after"
mark "form-authored revision approved and in force"

step "exporting the same set to files and applying it back unchanged"
stamp_cli policy export --dir /var/lib/stamp/export
EXPORTED=$(stamp_cli policy apply --dir /var/lib/stamp/export)
printf '%s\n' "$EXPORTED" | grep -q 'no change' \
  || die "re-applying the export proposed a revision; the round trip is not lossless:\n$EXPORTED"
ok "export → apply is a no-op: the two authoring paths agree on the same set"
mark "file round trip verified"

# ---------------------------------------------------------------------------
# 12. audit
# ---------------------------------------------------------------------------

step "verifying the audit chain against its signed checkpoints"
note "waiting for a checkpoint to be signed (the demo takes one every 10s)"
# Run the way an auditor runs it: the public key and a readable sink, and no
# signing key in the environment at all. That is the whole argument for
# checkpoints — whoever can rewrite the log can recompute every hash in it, and
# what they cannot do is produce this signature.
for _ in $(seq 1 40); do
  if "${COMPOSE[@]}" exec -T \
      -e STAMP_AUDIT_CHECKPOINT_KEY_FILE= \
      -e STAMP_AUDIT_CHECKPOINT_KEY_ID= \
      -e STAMP_AUDIT_CHECKPOINT_VERIFY_KEYS=demo-checkpoint=/var/lib/stamp/checkpoint.pub \
      stamp /stamp audit verify \
      --dsn "postgres://stamp:$DEMO_POSTGRES_PASSWORD@postgres:5432/stamp?sslmode=disable" \
      --sink /var/lib/stamp/checkpoints.jsonl >"$RUN_DIR/audit-verify.txt" 2>&1; then
    AUDIT_RC=0; break
  else
    # The capture has to be inside the else. After `fi` the status is the
    # status of the `if` statement, and an `if` whose condition was false with
    # no else exits 0 -- so a chain mismatch (6) read as a pass, and the
    # retry-on-7 loop below compared 0 to 7 and broke on the first pass.
    AUDIT_RC=$?
  fi
  [ "$AUDIT_RC" -eq 7 ] || break
  sleep 3
done
if [ "${AUDIT_RC:-1}" -ne 0 ]; then
  cat "$RUN_DIR/audit-verify.txt" >&2
  die "stamp audit verify exited $AUDIT_RC (0 verified, 6 mismatch, 7 no verdict)"
fi
sed -n '1,12p' "$RUN_DIR/audit-verify.txt" | sed 's/^/     /'
ok "stamp audit verify exited 0"
mark "audit chain verified"

# ---------------------------------------------------------------------------
# 13. two negative checks
# ---------------------------------------------------------------------------

step "a policy set that reaches outside is refused when no egress is allowed"
# The gate is deployment configuration, not policy data (D21/R35): a schema
# names a source, an operator decides what that source may dial. With no
# allowlist there is no destination that passes, so the process refuses to come
# up at all rather than starting with a source it can never call.
EGRESS_LOG="$RUN_DIR/egress-refusal.txt"
if "${COMPOSE[@]}" run --rm --no-deps \
     -e STAMP_AUDIT_WRITER_ID=egress-probe \
     -e STAMP_INSTANCE_ID=egress-probe \
     -e STAMP_EGRESS_ALLOW= \
     -e STAMP_STREAM_SOURCES= \
     -e STAMP_INGEST_CREDENTIALS= \
     -e STAMP_FACT_SOURCES='[{"name":"sanctions_list","kind":"http","params":[{"name":"destination","type":"string"}],"returns":"list<string>","ttl":"60s","timeout":"2s","url":"https://sanctions.example/v1/list"}]' \
     stamp --roles=all >"$EGRESS_LOG" 2>&1; then
  cat "$EGRESS_LOG" >&2
  die "the process started with a remote fact source and no egress allowlist"
fi
grep -qi 'egress' "$EGRESS_LOG" || { cat "$EGRESS_LOG" >&2; die "the refusal did not name the egress gate"; }
ok "refused, naming the egress gate: $(grep -io 'egress[^"]*' "$EGRESS_LOG" | head -1 | cut -c1-90)"

step "no plaintext secret in what the deployment renders or logs"
LOGS=$("${COMPOSE[@]}" logs --no-color 2>/dev/null || true)
# An empty LOGS would make every match below miss and report a green scan it
# never performed -- the same shape as the audit guard above. The logs of a
# running stack are never empty, so emptiness means the read failed.
[ -n "$LOGS" ] || die "could not read the stack's logs; the secret scan would have passed without looking"
CONFIG_DOC=$(curl -fsS "$CONSOLE/console/config.json")
for name in DEMO_POSTGRES_PASSWORD DEMO_KEYCLOAK_ADMIN_PASSWORD DEMO_USER_PASSWORD \
            DEMO_PEP_CLIENT_SECRET DEMO_INGEST_CLIENT_SECRET; do
  value=${!name}
  case "$LOGS" in *"$value"*) die "$name appears in container logs" ;; esac
  case "$CONFIG_DOC" in *"$value"*) die "$name appears in the console configuration document" ;; esac
done
case "$LOGS" in *"BEGIN PRIVATE KEY"*) die "a private key appears in container logs" ;; esac
ok "five generated credentials and the checkpoint key: none of them in logs or in /console/config.json"
note "the console's configuration document names the API base and the IdP and nothing else:"
printf '%s' "$CONFIG_DOC" | jq -c . | sed 's/^/     /'

# ---------------------------------------------------------------------------
# done
# ---------------------------------------------------------------------------

TOTAL=$((SECONDS - START_EPOCH))
mark "quickstart complete"

{
  printf 'profile: %s\n' "$PROFILE"
  printf 'started: %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  printf '\n'
  for t in "${TIMINGS[@]}"; do printf '%s\n' "$t"; done
  printf '\ntotal: %ds\n' "$TOTAL"
} >"$RUN_DIR/quickstart-timings-$PROFILE.txt"

printf '\n%s%s profile: check, decide-with-approval, velocity deny, form authoring,\n' "$GREEN" "$PROFILE"
printf 'file round trip and audit verification all succeeded in %ds.%s\n' "$TOTAL" "$OFF"
printf 'timings: %s\n' "$RUN_DIR/quickstart-timings-$PROFILE.txt"
if [ "$KEEP" -eq 1 ]; then
  printf '\nthe stack is still up:\n'
  printf '  console  %s/console/  (log in as ann; the password is in %s)\n' "$CONSOLE" "$ENV_FILE"
  printf '  idp      http://localhost:%s/admin/  (admin / DEMO_KEYCLOAK_ADMIN_PASSWORD)\n' "$KEYCLOAK_PORT"
  printf '  down     docker compose -f deploy/demo/docker-compose.yml down -v\n'
fi
